### ISSUE TITLE
BindAsync on Linux

### ISSUE THREAD

**Issue by Mariastakh** [flamencist/ldap4net#104]
Hello, 

Great library so far, got a little issue.

**The bug**
Running BindAsync on Linux causes a null reference exception

```
An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at LdapForNet.Native.LdapNativeLinux.<>c__DisplayClass10_0.<BindSimpleAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at LdapForNet.Native.LdapNativeLinux.BindSimpleAsync(SafeHandle ld, String userDn, String password, LDAP_TIMEVAL timeout)
   at LdapForNet.LdapConnection.BindAsync(LdapAuthType authType, LdapCredential ldapCredential)
   at LdapClient.Hello() in /path/to/the/Project/LdapClient.cs:line 16
```

**To Reproduce**
```
using var cn = new LdapConnection();
cn.Connect(new Uri("ldaps://example.co.uk"));
await cn.BindAsync(LdapAuthType.Simple, new LdapCredential());
```

**Expected behaviour**
Expected bind to be successful and to receive search results, however got a null reference exception from BindAsync(). The non async version of Bind() works fine by the way.

**Desktop:**
 - OS: [Linux]
 - Library version [2.7.11]
 - .NET\core\mono version [3.1]
 - LDAP server [OpenLdap 2.4.54-1]

**Comment by flamencist** [comment]
Hello! For simple auth binding you should specify username/dn and password.

**Comment by Mariastakh** [comment]
Hi!

It still fails with 
```
await cn.BindAsync(LdapAuthType.Anonymous, new LdapCredential());
```

With the same error
```
System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at LdapForNet.Native.LdapNativeLinux.<>c__DisplayClass10_0.<BindSimpleAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at LdapForNet.Native.LdapNativeLinux.BindSimpleAsync(SafeHandle ld, String userDn, String password, LDAP_TIMEVAL timeout)
   at LdapForNet.LdapConnection.BindAsync(LdapAuthType authType, LdapCredential ldapCredential)
   at LdapClient.Hello() in path/to/Project/LdapClient.cs:line 16
```
It works with **BindAsync** on windows, and it works with **Bind** but not **BindAsync** on Linux.

We have managed to replicate the issue in docker and the set up is

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1
RUN apt-get update
RUN apt-get install ldap-utils -y
```

**Comment by flamencist** [comment]
What linux distributive ?

**Comment by Mariastakh** [comment]
The distribution is Manjaro

We've just uploaded a repository over here with an example that reproduces the error

https://github.com/millsaj/ldapfornet-test

From trying to isolate the issue, it looks like **BindAsync** on Linux either doesn't like binding using **LdapAuthType.Anonymous**, or it does not like connecting over secure LDAP
