### ISSUE TITLE
Unable to use LdapForNet with libldap 2.6 on linux

### ISSUE THREAD

**Issue by vossjannik** [flamencist/ldap4net#140]
**Describe the bug**
I am using the newest version of the `libldap` package on arch linux: 2.6.0-2
https://archlinux.org/packages/core/x86_64/libldap/

When I try to initialize the LdapForNet library, I get the following error:

```txt
System.DllNotFoundException: Unable to load shared library 'ldap-2.4.so.2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libldap-2.4.so.2: cannot open shared object file: No such file or directory
   at LdapForNet.Native.NativeMethodsLinux.ldap_initialize(IntPtr& ld, String uri)
   at LdapForNet.Native.LdapNativeLinux.Init(IntPtr& ld, String url)
   at LdapForNet.LdapConnection.Connect(String url, LdapVersion version)
   at LdapForNet.LdapConnectExtensions.Connect(ILdapConnection connection, Uri uri, LdapVersion version)
   at LdapForNet.LdapConnectExtensions.Connect(ILdapConnection connection, String hostname, Int32 port, LdapSchema ldapSchema, LdapVersion version)
   at Ldap.Client..ctor(String host, Int32 port, Boolean tls, Boolean trustAll, TimeSpan timeout, Boolean chaseReferrals)
```

The filenames of the .so files are hardcoded in this library:
```c#
        private const string LIB_LDAP_PATH = "ldap-2.4.so.2";
        private const string LIB_LBER_PATH = "lber-2.4.so.2";
```
(Excerpt from "ldap4net/LdapForNet/Native/NativeMethodsLinux.cs")

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Library version: 2.7

**Comment by flamencist** [comment]
In .net we have two options for using a few versions of the native library: 
* simple option, just to create duplicates class of some native methods
* using dynamic function invoker, more complex, need to find libraries and procedure address, but without duplicated code
So I will appreciate it if someone helps me to port ldap4net for new OpenLDAP libraries

**Comment by fradav** [comment]
> * OS: Arch Linux
> * Library version: 2.7

Simple workaround, at least for Arch, just install [AUR libldap24](https://aur.archlinux.org/packages/libldap24), it doesn't replace 
current libldap.
