### ISSUE TITLE
Connection to LDAP fails on consecutive attempt. Linux (Docker)

### ISSUE THREAD

**Issue by oorobets** [flamencist/ldap4net#144]
**Describe the bug**
Binding fails on consecutive call in Linux. This issue **is not** present on Windows.

**To Reproduce**
```
class Program
    {
        static async Task Main(string[] args)
        {
            for (int i = 0; i < 5; i++)
            {
                using (var cn = new LdapConnection())
                {
                    cn.Connect("myldap.example.com", 636, Native.LdapSchema.LDAPS);
                    cn.TrustAllCertificates();
                    await cn.BindAsync(Native.LdapAuthType.Simple, new LdapCredential
                    {
                        UserName = "username",
                        Password = "password",
                        Realm = "EXAMPLE.COM",
                    });
                    var results = await cn.SearchAsync("dc=EXAMPLE,dc=COM", "my_filter");
                    foreach (var item in results)
                    {
                        Console.WriteLine(item);
                    }
                }
            }
        }
    }
```

**Expected behavior**
Consecutive connection should succeed 

**Desktop (please complete the following information):**
 - OS: Debian 11 (Docker)
 - Library version : 2.7.13
 - .NET\core\mono version: .NET 6, .NET 5
 - LDAP server: Active Directory

**Additional context**
```
Unhandled exception. LdapForNet.LdapOperationsErrorException: Operations error. 000004DC: LdapErr: DSID-0C090A71, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839. Result: 1. Method: ldap_parse_result. Details: ErrorMessage: 000004DC: LdapErr: DSID-0C090A71, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839
   at LdapForNet.Native.LdapNative.ThrowIfError(SafeHandle ld, Int32 res, String method, IDictionary`2 details)
   at LdapForNet.LdapConnection.ThrowIfResponseError(DirectoryResponse response)
   at LdapForNet.LdapConnection.SendRequestAsync(DirectoryRequest directoryRequest, CancellationToken token)
   at LdapForNet.LdapConnection.SearchAsync(String base, String filter, String[] attributes, LdapSearchScope scope, CancellationToken token)
```

Dockerfile
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0
RUN apt-get update \  
    && apt-get install -y --no-install-recommends libldap-2.4-2 \ 
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y ldap-utils libsasl2-2 libsasl2-modules sasl2-bin libsasl2-modules-ldap openssl
```

**Comment by oorobets** [comment]
Is LdapConnection object thread-safe? Can we reuse it?

**Comment by flamencist** [comment]
Please see into system log and try to use the sync version of Bind. Should be thread-safe

**Comment by oorobets** [comment]
Works!!!! Thank you so much!!!!!!
I used your [install.sh](https://github.com/flamencist/ldap4net/blob/a126279e6cfc14547d762f8cff23ee0568bce956/.test_config/install.sh) and did 
```
addhost example
addhost example.com
```
Verified on .NET 5

P.S. Works with `BindAsync()`
