### ISSUE TITLE
GetRootDse: An item with the same key has already been added. Key: subschemaSubentry

### ISSUE THREAD

**Issue by fubar-coder** [flamencist/ldap4net#162]
**Describe the bug**

When I call `GetRootDse` while connected to an Active Directory or HCL Domino Server, I get the following exception: `An item with the same key has already been added. Key: subschemaSubentry`

**To Reproduce**

```csharp
using var cn = new LdapConnection();

cn.Connect("LDAP://ldap-server");
await cn.BindAsync(Native.LdapAuthType.Simple, new LdapCredential()
{
    UserName = "user-name",
    Password = "user-password",
});

var rootDse = cn.GetRootDse();
```

**Expected behavior**

I expect a successful response for the `GetRootDse` function.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Library version: 2.7.14
 - .NET\core\mono version: .NET 6.0
 - LDAP server: Active Directory (Windows Server 2012 R2), HCL Domino Server 12.0.1

**Additional context**

The stack trace:

```text
System.ArgumentException: An item with the same key has already been added. Key: subschemaSubentry
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Collections.ObjectModel.KeyedCollection`2.AddKey(TKey key, TItem item)
   at System.Collections.ObjectModel.KeyedCollection`2.InsertItem(Int32 index, TItem item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at LdapForNet.LdapSearchExtensions.GetRootDse(ILdapConnection connection)
   at TestDomninoLdap.TestLdapForNet.RunAsync() in C:\Users\fubar\RiderProjects\TestDomninoLdap\TestDomninoLdap\TestLdapForNet.cs:line 28
   at Program.<Main>$(String[] args) in C:\Users\fubar\RiderProjects\TestDomninoLdap\TestDomninoLdap\Program.cs:line 3
   at Program.<Main>(String[] args)
```

Data from the LDAP browser:

![grafik](https://user-images.githubusercontent.com/4739844/159449667-b4d6bd45-40c5-4d12-bfe0-830719e99f3a.png)

It seems that there is only one "subschemasubentry" entry.

The function `GetRootDse` executes two searches and the `DirectoryAttribute` of the second search is a different instance than the `DirectoryAttribute` of the first search, which causes `IndexOf` to always return `-1`. The solution would be to change the `GetRootDse` in the following way:

```csharp
public static LdapEntry GetRootDse(this ILdapConnection connection)
{
    var result = connection.Search(null, "(objectclass=*)",
            new[]
            {
                "namingContexts", "subschemaSubentry", "supportedLDAPVersion", "supportedSASLMechanisms",
                "supportedExtension", "supportedControl", "supportedFeatures", "vendorName", "vendorVersion"
            }, LdapSearchScope.LDAP_SCOPE_BASE)
        .FirstOrDefault();
    if (result == null)
    {
        return null;
    }

    var rootDse = connection.Search(null, "(objectclass=*)", scope: LdapSearchScope.LDAP_SCOPE_BASE).First();
    foreach (var attribute in rootDse.DirectoryAttributes)
    {
        // Removes the attribute if it contains one with the given name
        result.DirectoryAttributes.Remove(attribute.Name);
        result.DirectoryAttributes.Add(attribute);
    }

    return result;
}
```

**Comment by flamencist** [comment]
Hi! Thank you for the catch
