### ISSUE TITLE
Unknown authentication method. SASL(-4): no mechanism available: No worthy mechs found. Result: -6. Method: BindSasl

### ISSUE THREAD

**Issue by yihango** [flamencist/ldap4net#183]
**Describe the bug**
error:
```txt
LdapForNet.LdapException: Unknown authentication method. SASL(-4): no mechanism available: No worthy mechs found. Result: -6. Method: BindSasl
   at LdapForNet.Native.LdapNative.ThrowIfError(SafeHandle ld, Int32 res, String method, IDictionary`2 details)
   at LdapForNet.LdapConnection.Bind(LdapAuthType authType, LdapCredential credential)
   at LdapTest.LdapForNetHelper.Ldap2(String domainIp, String domain, String userName, String pwd, String searchFilter) in D:\dev\staneee\ldap-test\LdapTest\LdapForNetHelper.cs:line 43
   at LdapTest.LdapForNetHelper.Run() in D:\dev\staneee\ldap-test\LdapTest\LdapForNetHelper.cs:line 20
```

dockerfile

```yml
FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base

RUN apt-get update \ 
    &&apt-get install -y --no-install-recommends libldap-2.4-2 \
    && apt-get install -y --no-install-recommends libldap-common \
    && ln -s -f /usr/lib/x86_64-linux-gnu/libldap-2.4.so.2 /usr/lib/ldap.so.2 \
    && ln -s -f /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 /usr/lib/lber.so.2
```

**To Reproduce**
![image](https://github.com/flamencist/ldap4net/assets/26987099/a0367447-1b54-4920-9a00-332ff9952119)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: docker ubuntu 20/04
 - Library version: 2.7.15
 - .NET\core\mono version: net6.0

**Additional context**

**Comment by nabanoub** [comment]
@staneee 

did you fix it?

**Comment by yihango** [comment]
> @staneee
> 
> did you fix it?

No, I haven't received any response at the moment.
I guess there is a problem with using the libldap version

**Comment by DanielMGoldberg** [comment]
Any luck ?
