### ISSUE TITLE
Inconsistent use of SafeHandle on win vs. mac/linux

### ISSUE THREAD

**Issue by gregbair** [flamencist/ldap4net#98]
**Describe the bug**
In [`TrustAllCertificates()`](https://github.com/flamencist/ldap4net/blob/master/LdapForNet/LdapConnection.cs#L296), the operation is delegated to the native classes.

In [linux](https://github.com/flamencist/ldap4net/blob/master/LdapForNet/Native/LdapNativeLinux.cs#L16) and [mac](https://github.com/flamencist/ldap4net/blob/master/LdapForNet/Native/LdapNativeOsx.cs#L19), a new `LdapHandle` is created and passed to `ldap_set_option`, meaning that this must be called _before_ `Connect()`, or else the option won't apply to the current connection, only subsequent ones.

However, on Windows, this doesn't work, as the call to [`ldap_get_option`](https://github.com/flamencist/ldap4net/blob/master/LdapForNet/Native/LdapNativeWindows.cs#L23) is called with the passed-in handle, meaning it must be called _after_ `Connect()`, as the handle is null until `Connect` is called.

I would create a PR for this, but I'm not sure which is the intended/correct behavior, but I suspect the Windows behavior is intended.

**To Reproduce**
```c#
using var connection = new LdapConnection();

connection.TrustAllCertificates(); // breaks on windows

connection.Connect();

connection.TrustAllCertificates(); // calling this here does not apply it to the current connection on mac/linux, only later ones
```

**Expected behavior**
Consistent behavior across platforms

**Desktop (please complete the following information):**
 - OS: All
 - Library version 2.7.22
 - .NET\core\mono version 3.1
 - LDAP server: OpenLdap

**Additional context**
Exception thrown on Windows:

```
System.ArgumentNullException: SafeHandle cannot be null. (Parameter 'pHandle')
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at LdapForNet.Native.NativeMethodsWindows.ldap_get_option(SafeHandle ld, Int32 option, Int32& value)
   at LdapForNet.Native.LdapNativeWindows.ldap_get_option(SafeHandle ld, Int32 option, Int32& value)
   at LdapForNet.Native.LdapNativeWindows.TrustAllCertificates(SafeHandle ld)
   at LdapForNet.LdapConnection.TrustAllCertificates()
```

**Comment by flamencist** [comment]
I will look

**Comment by flamencist** [comment]
You could use ```TrustAllCertificates``` for SSL only. So if use SSL you should specify SSL port in ```Connect``` method.
Otherwise if you need TLS you should use ```StartTransportLayerSecurity(true)```

**Comment by gregbair** [comment]
Sorry, that was just an example. We do specify the address in `Connect`.  It's more like `connnection.Connect("ldaps://host");`.

**Comment by flamencist** [comment]
Hm.. its worked for me in tests.

**Comment by gregbair** [comment]
I'll see if I can get a quick repro up this afternoon. I'm not on windows, so I'm working with one of my coworkers to reproduce/test.

Thanks!

**Comment by gregbair** [comment]
I'll work on a repro. We've got a workaround in our code.
